[package]
name = "LoudnessMeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hb_error = "0.1"
eframe = "0.20"
cpal = "0.14.0"
rustfft = "6.0.1"
